# Generated by Django 2.1.7 on 2019-03-24 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20190324_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ganesh',
            old_name='text',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='ganesh',
            old_name='name',
            new_name='Name',
        ),
    ]
